# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songs_title',
            new_name='song_title',
        ),
    ]
